### ISSUE TITLE
Node v4 (and v5) support

### ISSUE THREAD

**Issue by mcollina** [uber/ringpop-node#244]
Is support for node v4 and v5 planned?

I think the most problematic bit is https://www.npmjs.com/package/toobusy which you can replace with https://www.npmjs.com/package/loopbench.
I couldn't run the test, it seems tchannel need to be updated first.

**Comment by benfleis** [comment]
Hi Matteo, thanks for the follow up!

v4/v5 support hasn't been much requested so far, but we will have a look into what it would take to support it in the future.

TChannel upgrade is already on our immediate radar, so that part should be resolved soon.

Re toobusy, what is problematic? It compiles on my box without issue, but that's a single data point. Can you attach any logs/stacks that might demonstrate what you saw?

**Comment by mcollina** [comment]
Toobusy does not support node v4/v5 yet:

```
$ node -v
v4.2.4
$ npm i toobusy
-
> toobusy@0.2.4 install /Users/matteo/node_modules/toobusy
> node-gyp rebuild

  CXX(target) Release/obj.target/toobusy/toobusy.o
../toobusy.cc:25:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> TooBusy(const Arguments& args) {
                            ^~~~~~~~~
                            v8::internal::Arguments
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../toobusy.cc:37:20: error: no matching function for call to 'True'
    return block ? True() : False();
                   ^~~~
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:8139:16: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Boolean> True(Isolate* isolate) {
               ^
../toobusy.cc:37:29: error: no matching function for call to 'False'
    return block ? True() : False();
                            ^~~~~
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:8148:16: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
Local<Boolean> False(Isolate* isolate) {
               ^
../toobusy.cc:40:30: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> ShutDown(const Arguments& args) {
                             ^~~~~~~~~
                             v8::internal::Arguments
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../toobusy.cc:45:12: error: no matching function for call to 'Undefined'
    return Undefined();
           ^~~~~~~~~
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:315:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../toobusy.cc:48:25: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Lag(const Arguments& args) {
                        ^~~~~~~~~
                        v8::internal::Arguments
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../toobusy.cc:49:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../toobusy.cc:50:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Integer::New(s_currentLag));
           ~~~~~ ^
../toobusy.cc:50:49: error: too few arguments to function call, expected 2, have 1
    return scope.Close(Integer::New(s_currentLag));
                       ~~~~~~~~~~~~             ^
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:2499:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../toobusy.cc:53:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> HighWaterMark(const Arguments& args) {
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../toobusy.cc:54:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../toobusy.cc:56:13: error: member access into incomplete type 'const v8::internal::Arguments'
    if (args.Length() >= 1) {
            ^
/Users/matteo/.node-gyp/4.2.4/include/node/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../toobusy.cc:57:18: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        if (!args[0]->IsNumber()) {
             ~~~~^~
../toobusy.cc:58:24: error: no member named 'ThrowException' in namespace 'v8'
            return v8::ThrowException(
                   ~~~~^
../toobusy.cc:60:33: error: no member named 'New' in 'v8::String'
                    v8::String::New("expected numeric first argument")));
                    ~~~~~~~~~~~~^
../toobusy.cc:62:23: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        int hwm = args[0]->Int32Value();
                  ~~~~^~
../toobusy.cc:64:24: error: no member named 'ThrowException' in namespace 'v8'
            return v8::ThrowException(
                   ~~~~^
../toobusy.cc:66:33: error: no member named 'New' in 'v8::String'
                    v8::String::New("maximum lag should be greater than 10ms")));
                    ~~~~~~~~~~~~^
../toobusy.cc:71:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Number::New(HIGH_WATER_MARK_MS));
           ~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/toobusy/toobusy.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/matteo/.nvm/versions/node/v4.2.4/bin/node" "/Users/matteo/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/matteo/Repositories/toobusy
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/matteo/.nvm/versions/node/v4.2.4/bin/node" "/Users/matteo/.nvm/versions/node/v4.2.4/bin/npm" "i" "toobusy"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! toobusy@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the toobusy@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the toobusy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls toobusy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matteo/npm-debug.log
``

**Comment by Raynos** [comment]
We replaced `toobusy` with `toobusyjs` for node4 compat and that worked for us.

**Comment by Raynos** [comment]
See https://github.com/rf/process-reporter/pull/11

**Comment by trygve-lie** [comment]
On node 5.x the current used version of farmhash fails to compile. Version 1.1.1 of farmhash seems to work: https://github.com/lovell/farmhash/commit/954e89d56993877d91d0819d70768d589a83f3fb

**Comment by sashahilton00** [comment]
Just submitted a PR to fix this here: https://github.com/uber/ringpop-node/pull/289

**Comment by kadishmal** [comment]
Should this issue be closed? I've just installed `ringpop` on Node `v6.9.3` and ran the included test successfully.

```
$ node --version
v6.9.3
$ npm test

> ringpop@10.17.0 test /Users/user/ringpop
> npm run jshint && node test/index.js | faucet


> ringpop@10.17.0 jshint /Users/user/ringpop
> jshint --verbose *.js lib/**/*.js server/**/*.js

# config endpoints
✓ config endpointscationWarning: _writableState.buffer is deprecated. Use _writableState.getBuffer instead.
✓ gossip endpoints
✓ test bi-directional full syncs
✓ test bi-directional full syncs throttles
✓ ping-reqs 1 member
✓ ping-reqs 3 members
✓ ping-req target unreachable
✓ no ping-req members
✓ some bad ping-statuses
✓ ping-req inconclusive
✓ bootstrap with self is ok
✓ one node can join
✓ two nodes can join
✓ three nodes can join
✓ three nodes, one of them bad, join size equals one
✓ three nodes, two of them bad, join size equals two
✓ do not disseminate join list
✓ mega cluster
✓ slow joiner
✓ join blacklist
✓ not-ready error on ping
✓ ping-req fails when not ready
✓ ping-req inconclusive when all ping-req nodes are not ready
✓ ping-req succeeds if one ping-req is successful
✓ send ping-reqs when a node is not ready
✓ healing - two nodes
✓ healing - two partitions of two nodes
✓ raise piggyback counter
✓ don't raise piggyback counter when ping fails
✓ handleOrProxy() returns true for me
✓ handleOrProxy() proxies for not me
✓ handleOrProxyAll() proxies and handles locally
✓ can proxyReq() to someone
✓ one retry
✓ two retries
✓ no retries, invalid checksum
✓ no retries, invalid checksum emit request when enforceConsistency is false
✓ exceeds max retries, errors out
✓ cleans up pending sends
✓ cleans up some pending sends
✓ overrides /proxy/req endpoint
✓ overrides /proxy/req endpoint and fails
✓ aborts retry because keys diverge
✓ retries multiple keys w/ same dest
✓ reroutes retry to local
✓ reroutes retry to remote
✓ can serialize url
✓ can serialize headers
✓ can serialize method
✓ can serialize httpVersion
✓ will timeout after default timeout
✓ can serialize body
✓ can serialize response statusCode
✓ can serialize response headers
✓ can serialize response body
✓ proxies buffer responses
✓ custom timeouts
✓ handle body failures
✓ non json head is ok
✓ handle tchannel failures
✓ handles checksum failures
✓ does not crash when forwarding request on closed socket
✓ send on destroyed channel not allowed
✓ proxies big json
✓ stuck requests
✓ too many requests in
✓ too many requests out
✓ too many requests in+out
✓ too much lag
✓ egress inflight to 0
✓ ingress inflight to 0
✓ lookup yourself returns yourself
✓ RingpopHandler proxies
✓ RingpopHandler to other node
✓ RingpopHandler for two
✓ RingpopHandler for two
✓ RingpopHandler blacklist
✓ RingpopHandler bad request
✓ waitForIdentified request after cancel
✓ subChannel request after cancel
✓ canceled request in correct state
✓ double cancel; callback already called
✓ retryLimit for protocol calls
✓ retryLimit defaults to 0
✓ number of inflight pings match number of tracked requests
✓ empties completed requests
✓ exceeds max inflight limit
✓ cancels correct number of requests
✓ emits ringpop error on canceled request
✓ set and get interactions
✓ changed events
✓ seeds known config
✓ no seed is OK
✓ validates memberBlacklist seed
✓ validates num
✓ damped max percentage
✓ damp-req selection unsatisfied
✓ sends n-val damp-reqs
✓ adds flapper
✓ does not add flapper if already damped
✓ does not add flapper twice
✓ starts damper after adding first flapper
✓ removes flapper
✓ does not remove flapper if never added
✓ stops damp timer if last flapper removed
✓ damps multiple members
✓ damp timer initiates subprotocol
✓ damping member starts expiration
✓ expires damped members
✓ expires no damped members
✓ deals with damp-req errors
✓ damp these members
✓ DiscoverProviderHealer - constructor
✓ DiscoverProviderHealer.heal - errors
✓ DiscoverProviderHeal.heal - random order
✓ DiscoverProviderHeal.heal - partition healed after one attempt
✓ DiscoverProviderHeal.heal - max failures
✓ DiscoverProviderHeal.heal - only attempt to heal faulty (or worse) nodes
✓ DiscoverProviderHeal.heal - never attempt to heal on self
✓ DiscoverProviderHealer - timers
✓ DiscoverProviderHealer - starts on ready
✓ static host list discover provider
✓ json file discover provider - success
✓ json file discover provider - error: non existing file
✓ json file discover provider - error: non json file
✓ discoverProvider createFromOpts
✓ with string-argument - uses hostsFile
✓ opts with bootstrapFile - uses hostsFile
✓ with array-argument - uses static hosts
✓ opts with hosts - uses static hosts
✓ with function - uses function
✓ opts with discoverProvider - uses function
✓ without arguments - returns null
✓ member ship as changes includes all members
✓ avoids redundant dissemination by filtering changes from source
✓ raise piggyback counter on issueAsReceiver
✓ raise piggyback counter on issueAsSender
✓ tombstone has priority vs other states
✓ issueAsReceiver returns whether a full sync is made
✓ tryStartReverseFullSync keeps track of running jobs
✓ tryStartReverseFullSync keeps track of running jobs
✓ tryStartReverseFullSync keeps track of running jobs on error
✓ tryStartReverseFullSync doesn't start reverse full sync when max jobs is 0
✓ tryStartReverseFullSync doesn't start reverse full sync when out of workers
✓ tryStartReverseFullSync send join request to target node
✓ starting and stopping gossip sets timer / unsets timers
✓ stopping gossip is a noop if gossip was never started
✓ gossip can be restarted
✓ suspect period for member is started
✓ suspect period cannot be started for local member
✓ starting the same state transition for a member is a noop
✓ starting a new state transition for a member stops the previous one
✓ suspect period can't be started until enabled
✓ state transition stop all clears all timers
✓ state transitions cannot be enabled without all timers first being stopped
✓ marks member faulty after suspect period
✓ marks member tombstone after faulty period
✓ evict member after tombstone period
✓ construct a new HashRing with defaults
✓ construct a new HashRing with options
✓ HashRing.addServer
✓ HashRing.removeServer
✓ checksum is null upon instantiation
✓ checksum is not null when server added
✓ checksum is still null when non-existent server removed
✓ checksum recomputed after server added, then removed
✓ servers added out of order result in same checksum
✓ servers removed out of order result in same checksum
✓ does not throw when calling lookup with 0 servers
✓ does not throw when calling lookup with an integer
✓ key hashes to only server
✓ admin join rejoins if member has previously left
✓ admin leave prevents redundant leave
✓ admin leave makes local member leave
✓ admin leave stops gossip
✓ admin leave stops state transitions
✓ protocol join disallows joining itself
✓ protocol join disallows joining different app clusters
✓ no opts does not break handleOrProxy
✓ registers stats hook
✓ stats include stat hooks
✓ fails all hook registration preconditions
✓ stat host/port should properly format IPs and hostnames
✓ emits membership changed event
✓ emits ring changed event
✓ max piggyback not adjusted on membership update
✓ max piggyback adjusted on new members
✓ first time member, not alive
✓ don't call tchannel with invalid host port pair
✓ don't call tchannel with invalid host port pair
✓ suspicionTimeout backward compatibility
✓ registerSelfEvictHook registers hook in self evicter
✓ selfEvict initiates self evict sequence
✓ no responses results in empty array
✓ responses with same checksum uses first response
✓ merges responses when checksums are null
✓ create a joiner
✓ create throws with no ringpop
✓ create throws with no bootstrap hosts
✓ inits all nodes on same host
✓ inits single node cluster
✓ inits multi-host cluster
✓ select group initializes node collections
✓ select multiple rounds of groups
✓ select group of preferred nodes
✓ select group of mixed nodes
✓ join after destroyed
✓ is status pingable
✓ status precedence is correct
✓ status precedence with unknown state never takes precedence
✓ test other override (alive)
✓ test other override (suspect)
✓ test other override (faulty)
✓ test other override (leave)
✓ test other override (tombstone)
✓ damp score intialized
✓ penalized for update
✓ flaps until exceeds suppress limit
✓ damp score never exceeds max
✓ penalized in penalty increments
✓ decays by some arbitrary amount
✓ decayed by half
✓ never decays below min
✓ member ID is its address
✓ checksum is changed when membership is updated
✓ change that overrides the local status should be overwritten to a change that reincarnates the node
✓ change that does not override the local status should not cause a reincarnation
✓ change with same incarnation number does not result in leave override (reincarnates)
✓ change with lower incarnation number does not result in leave override
✓ member is able to go from alive to faulty without going through suspect
✓ leave does not cause neverending updates
✓ evict removes a member
✓ cannot evict self
✓ generate checksums string preserves order of members
✓ sets previously stashed updates
✓ set merges stashed updates
✓ set adds all members
✓ set emits an event
✓ set computes a checksum once
✓ set does not shuffle member positions
✓ starts decayer on init
✓ unsets decayer timer on stop
✓ respects decayer enabled config
✓ decayer decays all damp scores
✓ update happens synchronously or not at all
✓ merges incarnation numbers
✓ iterates over two members correctly
✓ iterates over three members correctly
✓ skips over faulty member and 1 local member
✓ starts state transition period for suspect
✓ track handles empty/invalid array
✓ track sets flush timer
✓ flushes buffer if time since last update exceeds flush interval
✓ flush multiple times
✓ initializes max num updates
✓ empty middleware stack
✓ empty middlewares in stack
✓ middlewares are applied in order
✓ middlewares with only one method
✓ caches loggers
✓ logs at correct level
✓ turn off gossip logging
✓ can log at
✓ proxyReq() proxies the request
✓ proxyReq enforces required args
✓ construct a new RBIterator
✓ RBIterator.val and RBIterator.str
✓ RBIterator.minNode
✓ RBIterator.next walk the entire tree
✓ construct a new RBTree
✓ RBTree.insert
✓ RBTree.remove
✓ RBTree insert dup
✓ RBTree insert remove insert
✓ RBTree lowerBound
✓ RBTree upperBound
✓ RBTree payload copy bug
# request proxy sends custom ringpop metadata in head
✓ request proxy sends custom ringpop metadata in head, use 'global'
✓ request proxy emits head
✓ request proxy passes down skipLookupOnRetry correctly
✓ request proxy consistency defaults
✓ request proxy - ring consistency: enabled
✓ returns error on invalid checksum
✓ handles on valid checksum
✓ request proxy - handles request with invalid checksum and ring consistency disabled
✓ request proxy - key consistency - returns error when key not owned by node
✓ request proxy - key consistency - emit stat once
✓ has correct number of servers on add/remove
✓ checksum computed only once
✓ 1000 lookups
✓ 1000 lookupN
✓ lookupN on ring of size 1
✓ lookupN on empty ring
✓ lookupN on corrupted ring of size 1
✓ lookupN on corrupted empty ring
✓ construct a new red node with supplied values
✓ getChild
✓ setChild
✓ ringpop without app throws
✓ ringpop without options throws
✓ ringpop with invalid hostPort
✓ constructor
✓ register hooks
✓ self evict sequence without hooks
✓ self evict sequence invokes hooks
✓ self evict completes when membership is empty
✓ self evict pings members to speed up gossip
✓ self evict ping count is correct
✓ self evict does not ping more than number of members
✓ self evict does not tick membership when "selfEvictionPingEnabled" is disabled
✓ initiate multiple times returns error
✓ config set handler validation
✓ config get/set handlers
✓ start/stop gossip
✓ healing via discovery provider
✓ healing via discovery provider - error path
✓ results in bad request
✓ responds with damp scores
✓ join fails with blacklist error
✓ join fails with bad hostPort as source
✓ join fails with bad hostPort as source
✓ join fails with bad hostPort as source
✓ join fails with bad hostPort as source
✓ join succeeds with correctly formatted hostPort as source
✓ join succeeds with correctly formatted hostPort as source
✓ periodic stats have correct defaults
✓ periodic stats respect period overrides
✓ periodic stats bounded by minimum
✓ ringChecksumPeriod honored if in bounds
✓ ringChecksumPeriod survives invalid option
✓ start/stop works too
✓ trace adds/removes work and are idempotent
✓ trace events get traced
✓ trace events can renew, and expire
✓ arg3 is JSON decoded
✓ if decoding fails, the arg is unchanged
✓ arg2 is JSON decoded for /proxy/req
✓ res2 is JSON encoded
✓ res2 is not JSON encoded if string
✓ buffer-res2 is not JSON encoded if string
# tests 3356
# pass  3356
✓ ok
```

**Comment by Raynos** [comment]
Works on node4 & node6 as far as I know.

**Comment by mcollina** [comment]
Closing then :)
