### ISSUE TITLE
Facing issue with npm install in ringpop-node

### ISSUE THREAD

**Issue by chandresh-pancholi** [uber/ringpop-node#279]
Hi, I was following instruction given on ringpop-node doc site.
While trying npm install i am getting errors[1].

Please help me to solve it.
[1]:https://gist.github.com/chandresh-pancholi/b79cf90c9d17d65437e9d37695f09704

**Comment by dansimau** [comment]
ringpop-node is only compatible with node v0.10.x at this point.

Can you try downgrading node?

**Comment by chandresh-pancholi** [comment]
Thank dan. While running ./scripts/tick-cluster.js -n 7 -i node ./main.js command. I am seeing 
module.js:340
    throw err;
          ^
Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/chandresh.pancholi/opensource/ringpop-node/scripts/tick-cluster.js:25:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by dansimau** [comment]
Did the `npm install` finish successfully?

`cli-color` is listed as a dev dependency in `package.json`:

```
dan-mbp-work:ringpop-node dan$ grep -rn cli-color package.json 
package.json:47:    "cli-color": "^0.3.2",
dan-mbp-work:ringpop-node dan$ 
```

I don't really have good internet right now so I can't try to reproduce this. But from the looks of things an `npm install` should install `cli-color`.

**Comment by chandresh-pancholi** [comment]
Actually i am using intellij node plugin which was overriding the dependencies. I am using Atom now and 
I am continuously getting  
> farmhash@1.1.0 install /Users/chandresh.pancholi/opensource/ringpop-node/node_modules/tchannel/node_modules/farmhash
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/path-platform
npm http 304 https://registry.npmjs.org/event-emitter

module.js:340
    throw err;
          ^
Error: Cannot find module **'readable-stream'**
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/npmlog/node_modules/are-we-there-yet/index.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by chandresh-pancholi** [comment]
Finally i am able to install ringpope-node.
Thank you Dan.
